name: invoiceapp
description: "Invoice & Estimation Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  pdf: ^3.11.0
  printing: ^5.13.3
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  open_file: ^3.5.10
  http: ^1.2.0
  shared_preferences: ^2.2.2
  barcode: ^2.2.8
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
